### ISSUE TITLE
Update readme to add an example of how to use the new filter

### ISSUE THREAD

**Issue by zacyang** [kontist/type-graphql-filter#3]
Hi 
I find it not very straight forward to use this lib as there's no example regarding how to use the filter as query parameter. Would be nice to have one. thanks.

**Comment by smolinari** [comment]
Um, don't you see the input types in your schema? That's one of the beauties of GraphQL. Introspection. :)

Scott

**Comment by zacyang** [comment]
Yeah, I am not worry about the query side at all actually. It's just the server side, when I got the filter, how to apply this function. In your example ```new ExampleLoader().load({
      filter // handle the filter with your business logic
    });``` for example, where is ExampleLoader ?

**Comment by smolinari** [comment]
Um, so you are thinking the filter is a function? How so? It should be an object.

Scott

**Comment by zacyang** [comment]
It's type is any and I am pretty new to the ts-gql world, so I would assume it's a function as filter does in most cases. But you are right it's an object, so my question is, do I need some context to use this (filter) object? or I just use the info in the object to do filter myself?

**Comment by smolinari** [comment]
The latter. Use the object as you need it to form your filter for your database query. 

Scott

**Comment by hihuz** [comment]
Hello @zacyang 👋 Sorry for the late reply.

The goal of this module is to generate the filter types for your graphql schema, however it is not aware of your business logic, so what you do with the filter you received from the query is up to you.

We designed the filter names using very common sql operators, which should make it fairly straightforward to transform them to actual sql / ORM code.

At Kontist we use this library to generate sequelize conditions from the query filters using a simple mapping function.
We might consider including this function to this library as a "sequelize connector" if there is any interest.

For a simplified example, you could consider writing such a function, passing it the filter object:
```typescript
const generateCondition = filter => {
    for (const [filterKey, filterValue] of Object.entries(filters)) {
          const [field, operator] = filterKey.split("_");

         // from that point on, if the filter in your query was { firstname_like: "john" } you have:
         // - the name of the field as 'field' variable, i.e. "firstname"
         // - the operator to filter this field as 'operator' variable, i.e. "like"
         // - the value of the filter as 'filterValue' variable, i.e. "john"
    }
}
```

Hope that helps

**Comment by johannespfeiffer** [comment]
Added to the README.md in https://github.com/kontist/type-graphql-filter/commit/5c3c2010124a7597f0c3f61e77d0d75b18a884f9
Thank you @hihuz 🙏
