### ISSUE TITLE
Creating default filter sets for types

### ISSUE THREAD

**Issue by smolinari** [kontist/type-graphql-filter#4]
Hi,

I was wondering, there seems to be a lot of repetition when creating the `@Filter` decorators for each field. Could there be a feature added to set up default filters depending on the type of the field?

Scott

**Comment by smolinari** [comment]
Actually, nevermind. I'm going to be creating filter input type factories, instead of using this library. The methodology of creating the types with the @Arg decorator isn't type safe in the end and goes against the architecture of Type-GraphQL, as the maker of Type-GraphQL, Michal, informed me. I'm still learning myself, so if that sounds strange to you, as it does to me, just take it for granted as I do, that Michal is a master at TypeScript and his framework and should know what he is talking about. 😄 

Scott

**Comment by smolinari** [comment]
The whole discussion, if you are interested:

![image](https://user-images.githubusercontent.com/3314957/89766954-46eefa00-daf9-11ea-895a-8ac76041d5ab.png)

Scott

**Comment by steinroe** [comment]
Thanks for pointing this out @smolinari . Do you have any examples on the generic types approach? I can't get my mind around how that could be solved elegantly.
