### ISSUE TITLE
Can't use enums in filter decorator - types problem

### ISSUE THREAD

**Issue by danielb7390** [kontist/type-graphql-filter#7]
I was trying to create a filter on a Enum field and ts was not happy.
Took a look at your types, and here you have way less possible types than the type-graphql types do.

https://github.com/kontist/type-graphql-filter/blob/5c3c2010124a7597f0c3f61e77d0d75b18a884f9/lib/types/metadata.ts#L5

type-graphql has
```
export declare type TypeValue = ClassType | GraphQLScalarType | Function | object | symbol;
export declare type ReturnTypeFuncValue = TypeValue | RecursiveArray<TypeValue>;
```
I added them manually to the .d.ts file and the enum filter is working fine.
Is there a reason for this or it's just missing and needs to be added?

**Comment by johannespfeiffer** [comment]
Thank you. Makes sense, merged your suggestion.
